### ISSUE TITLE
method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by Donhv** [MaxToyberman/react-native-locale-listener#3]
F:\Android\React Native\AwesomeProject\node_modules\react-native-locale-listener\android\src\main\java\com\toyberman\localeReload\RNReactNativeLocalePackage.java:20: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-locale-listener:compileReleaseJavaWithJavac

**Comment by adnanali-indpro** [comment]
use the current react natve facebook version or remove that override method because its available for current version

**Comment by RidaRidss** [comment]
RNReactNativeLocalePackage.java should be look like this

package com.toyberman.localeReload;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;
import com.facebook.react.bridge.JavaScriptModule;

public class RNReactNativeLocalePackage implements ReactPackage {
    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
      return Arrays.<NativeModule>asList(new RNReactNativeLocaleModule(reactContext));
    }

<! -- add comment here ------- >
    // @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
      return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
      return Arrays.asList();
    }
}

this worked for me  💯

**Comment by MaxToyberman** [comment]
@Donhv  fixed in the new version
